### ISSUE TITLE
huge amount of errors printed to pd console

### ISSUE THREAD

**Issue by olilarkin** [CICM/CreamLibrary#11]
with pd vanilla 0.46.6 on OSX 10.95 i get a lot of errors when mousing over objects in the 0.3 release version

Bad arguments for message 'focus' to object 'c.number'
Bad arguments for message 'focus' to object 'c.number'
Bad arguments for message 'focus' to object 'c.number'
Bad arguments for message 'mouseleave' to object 'c.knob'
Bad arguments for message 'focus' to object 'c.number'
Bad arguments for message 'focus' to object 'c.number'
Bad arguments for message 'focus' to object 'c.number'
Bad arguments for message 'focus' to object 'c.number'
Bad arguments for message 'focus' to object 'c.number'
Bad arguments for message 'focus' to object 'c.number'
Bad arguments for message 'focus' to object 'c.number'
Bad arguments for message 'focus' to object 'c.number'
Bad arguments for message 'focus' to object 'c.number'
Bad arguments for message 'focus' to object 'c.number'
Bad arguments for message 'focus' to object 'c.number'
Bad arguments for message 'focus' to object 'c.number'
Bad arguments for message 'focus' to object 'c.number'
Bad arguments for mess

**Comment by pierreguillot** [comment]
Yes I know, PD 0.46 has changed the arguments behavior in the methods. The problem is already corrected but I won't publish an "official" release before the next version of the HOA library. I know that all the messages are really boring nevertheless this should still work so you have 4 temporary solutions :
1 - wait...
2 - compile the last version with Xcode.
3 - compile the last version with the makefile (see readme)
4 - download this pre-release :
https://dl.dropboxusercontent.com/u/21891549/HoaCream.zip

> If you use HOA, you should also install or compile the last pre-release.

Cheers
